### ISSUE TITLE
Unify the configuration style

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1081]
**Affected version(s)**

4.9

**Description**  

I just noticed that most of the bundle configuration uses snake case but a few recently introduced configuration keys use camel case.
We should definitely review those before the release.

**Comment by leofeyer** [comment]
Which one for instance?

**Comment by Toflar** [comment]
* `contao.search.indexProtected`
* `contao.crawl.additionalURIs`
* `contao.crawl.defaultHttpClientOptions`

But also some that are already stable. Children of `contao.image.sizes` for example.

**Comment by aschempp** [comment]
imho container configuration is and should always be snake_case. I haven't seen camelCase anywhere in Symfony.

**Comment by leofeyer** [comment]
See #1155 for the fix for the new parameters. We have also added "wrong" parameters in #537:

```yaml
contao:
    image:
        sizes:
            foobar:
                width: 100
                height: 200
                resizeMode: 'box'
                zoom: 100
                cssClass: 'foobar-image'
                densities: '1x, 2x'
                sizes: '100vw'
```

Shall I try to fix these as well?
