### ISSUE TITLE
Datenschutz: fehlende Security-Header

### ISSUE THREAD

**Issue by chriza** [contao/contao#1174]
Der Datenschutzdienstleister einer meiner Kunden, hat fehlende Security Header angemahnt. Diese fehlen auch bei contao.org

https://securityheaders.com/?q=contao.org%2F&followRedirects=on

**Comment by richardhj** [comment]
Du kannst die Header manuell hinzufügen:

Folgender Event-Listener im App Bundle:
```php
// add the new use statement at the top of your file
use Symfony\Component\HttpKernel\Event\ResponseEvent;

public function onKernelResponse(ResponseEvent $event)
{
    $response = $event->getResponse();

    $response->headers->set('Content-Security-Policy', 'foo');
    $response->headers->set('Feature-Policy', 'foo');
}

public static function getSubscribedEvents()
{
    return [
        KernelEvents::RESPONSE => 'onKernelResponse',
    ];
}

```

**Comment by fritzmg** [comment]
Die musst du selbst setzen. Das kann imho nicht pauschal vorgegeben werden.

Beides kannst du über das nelmio/security-bundle setzen lassen, afaik.

// Richard war schneller :)

**Comment by akroii** [comment]
`config.yml`

```
# Contao configuration
contao:
    url_suffix: ''
    image:
        imagine_options:
            jpeg_quality: 100
# Security configuration
nelmio_security:
    xss_protection:
        enabled: true
        mode_block: true
    forced_ssl:
        enabled: true
        hsts_max_age: 2592000
        hsts_subdomains: true
        redirect_status_code: 301
    csp:
        enabled: true
        hash:
            algorithm: sha256
        enforce:
            level1_fallback: false
            img-src:
                - '* data: unsafe-inline'
            default-src:
                - '*'
                - 'unsafe-eval'
                - 'unsafe-inline'
            script-src:
                - '*'
                - 'unsafe-eval'
                - 'unsafe-inline'
```

Danach musst du im Manager den Prod löschen. Danach musst du deine Seite testen ob in der browser Console die Seite noch läuft... oder ob es Fehler gibt.
