### ISSUE TITLE
Map the app entities by default

### ISSUE THREAD

**Issue by qzminski** [contao/contao#1434]
**Description**
The Doctrine entities inside `App` namespace could probably be mapped by default. This requires some changes in the current config skeleton: https://github.com/contao/contao/blob/master/manager-bundle/src/Resources/skeleton/config/config.yml#L54

**Example**
As of now I have to provide this configuration on my own:

```yaml
doctrine:
    orm:
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                is_bundle: false
                prefix: App\Entity
                alias: App
```

/cc @aschempp
