### ISSUE TITLE
Override page dns settings by configuration

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#1517]
When having a Contao project on multiple stages and in custom developer environments the page dns settings has always be adjusted. Automated processes require the extra database manipulation to adopt these settings. 

After discussing this limitation with a customer of mine, the idea came up to override the page dns settings by a configuration file. So it would be possible to change the dns entries depending on your environment.

A possible configuration structure might be:

```yaml
contao:
  routing:
    override_dns:
       # DNS entry defined in the root page
       example.org:
         dns: staging.example.org
         ssl: false
```

Now Contao would always use staging.example.org for the pages where the dns setting is set to `example.org`.

Wdyt?
