### ISSUE TITLE
Redirection problems when running insecure installation

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1529]
**Affected version(s)**
Contao 4.9.0

**Description**
When running a Contao installation from within a subfolder (e.g. http://example.com/mycustomer/web/) instead of a dedicated domain there are all kinds of problems with faulty redirects:

- Enabling the Debug-Mode redirects to `http://example.com/contao/` instead of `http://example.com/mycustomer/web/contao/`
- Clicking on preview redirects to `http://example.com/preview.php/mycustomer/web/contao/preview` instead of `http://example.com/mycustomer/web/preview.php/`
- Clicking on the icon of a page in tl_page also redirects to the wrong preview

**Comment by fritzmg** [comment]
You cannot run Contao 4 from a subfolder, except on localhost.

**Comment by bennyborn** [comment]
Of course you can. That's been working for years prior to 4.9 by adding the following to the `parameters.yml`

```yml
services:
    contao.listener.insecure_installation:
        class: Contao\CoreBundle\EventListener\InsecureInstallationListener
```
