### ISSUE TITLE
make notification bell counter more visible

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#191]
Imho the counter on the notification bell currently goes unnoticed pretty easily (red on orange). Just a small suggestion on how it could look differently:

![nb_org](https://user-images.githubusercontent.com/4970961/48660514-1cc2f200-ea63-11e8-8860-1dcc20b19b3a.png)

vs.

![nb_alt1](https://user-images.githubusercontent.com/4970961/48660516-20ef0f80-ea63-11e8-8430-64dfd60668fc.png)

Example with bigger numbers:

![nb_alt2](https://user-images.githubusercontent.com/4970961/48660518-251b2d00-ea63-11e8-957e-6e4a75d45030.png)

CSS used:

```css
{
  top: 4px;
  left: 20px;
  width: 18px;
  height: 18px;
  background-color: white;
  color: red;
  text-align: center;
  line-height: 18px;
  font-size: 10px;
  border-radius: 100%;
  padding: 0;
  font-weight: 700;
}
```

Any thoughts? :)
