### ISSUE TITLE
Introduce dedicated config variable for legacy routing

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1993]
Currently, the legacy routing is automatically enabled, if either the `contao.prepend_locale` or `contao.url_suffix` config is set (no matter what value). This is fine for setups that already use this config - however, in setups where legacy routing is needed, but neither the language parameter in the URL nor a different URL suffix is needed, it seems counter intuitive to have to set either. For the conscious of the Contao community it might feel especially unusual to set `contao.prepend_locale` to `false`, since that is counter intuitive (the language parameter is disabled by default anyway).

So how about creating a new `contao.legacy_routing` config variable, that can be used _in addition_? i.e. the current logic still applies (legacy routing will be enabled when either `contao.prepend_locale` or `contao.url_suffix` is set), but additionally you can also activate it via

```yml
# config/config.yml
contao:
    legacy_routing: true
```

Also, misconfigurations like

```yml
# config/config.yml
contao:
    prepend_locale: true
    legacy_routing: false
```

could be validated directly in the `Configuration`. 

The parameter `contao.legacy_routing` is already set by the `ContaoCoreExtension` anyway, so why not make it configurable directly as well?
