### ISSUE TITLE
Missing CSS property for pre.sf-dump

### ISSUE THREAD

**Issue by Aybee** [contao/contao#2058]
**Affected version(s)**

Seen in 4.9.4

**Description**

There's a Rocksolid theme with this CSS rule.
```css
pre {
  background-image: linear-gradient(to bottom, #ececec 50%, #232323 50%);
}
```
This makes the output of `$this->dumpTemplateVars();` unreadable.

Following rule will correct this.
```css
pre.sf-dump {
  background-image: none;
}
```
