### ISSUE TITLE
Default values for contao:image:sizes config

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2198]
Our image config allows defining individual sizes with lots of specific options. But often times these sizes share some common settings that are repeated over and over in the config.

Example (see `formats`, `sizes`, `lazy_loading`, `resize_mode` for instance):

```yaml
contao:
  image:
    sizes:
      large_photo:
        formats:
          jpg:
            - webp
            - jpg
        sizes: '0.75,1,2'
        lazy_loading: true
        resize_mode: crop
        width: 1000
        height: 500

      medium_photo:
        formats:
          jpg:
            - webp
            - jpg
        sizes: '0.75,1,2'
        lazy_loading: true
        resize_mode: crop
        width: 500
        height: 250

      small_box:
        formats:
          jpg:
            - webp
            - jpg
        sizes: '1,2'
        resize_mode: box
        width: 100
        height: 100
```

Yaml allows reusing config with anchors (`key: &anchor` + `<<: *anchor`) but this concept is very limited (recursive merging?, needs a dummy element, ...). We could, however, introduce a `_defaults` size which will be merged with the explicitly defined options when creating the `PictureConfiguration`. The example from above could then look like this:

```yaml
contao:
  image:
    sizes:
      _defaults:
        formats:
          jpg:
            - webp
            - jpg
        sizes: '0.75,1,2'
        lazy_loading: true
        resize_mode: crop
          
      large_photo:
        width: 1000
        height: 500

      medium_photo:
        width: 500
        height: 250

      small_box:
        sizes: '1,2'
        resize_mode: box
        width: 100
        height: 100
```

This could in theory even serve as the defaults when creating a config in the backend, but I think I'd only use it for the yaml-defined config.

Wdyt?
