### ISSUE TITLE
Crawler requires valid SSL

### ISSUE THREAD

**Issue by Metis77** [contao/contao#2504]
**Affected version(s)**
Contao 4.9

**Description**
The Crawler (building search index) requires a valid SSL, that we usually do not have in local developement.

`Exception of type "Symfony\Component\HttpClient\Exception\TransportException" occurred: SSL peer certificate or SSH remote key was not OK for "https://eltern-zeitung.local/eltern-zeitung".`

I think it would be best, if also invalid SSL is allowed.

**Comment by Toflar** [comment]
You can disable that for yourself if you want to. It's certainly not a good default to ignore TLS validation...
```
contao:
    crawl:
        default_http_client_options:
            verify_peer: false
```
