### ISSUE TITLE
Have a label for predefined image sizes

### ISSUE THREAD

**Issue by bezin** [contao/contao#2589]
Since Contao 4.8 we can predefine image sizes in `config.yml` which is a great feature. 
I prefer to give them English names, as I will use these in my custom module and content element classes and I do not like mixing languages in the code; However, for the back end user I would like to define a meaningful label in German. 

It would be nice to have a label attribute, that may differ from the name attribute:

```
# config.yaml
contao:
  image:
    sizes:
      contact:
        label: 'Kontakt'
# ...
```

**Comment by m-vo** [comment]
Isn't this already possible with translations?

**Comment by fritzmg** [comment]
You can use translations for that :)

```yml
# config/config.yml
contao:
    image:
        sizes:
            default:
                width: 1024
                densities: 1.5x
```

```yml
# translations/image_sizes.yml
default: 'Default image size'
```

However, we do lack proper documentation for this currently. Ideally I think we should have an article for the image sizes management [here](https://docs.contao.org/manual/en/layout/theme-manager/) plus then also a description on how to pre-define image sizes in your config as well as how to translate the labels for the back end.
