### ISSUE TITLE
SessionTimeout in config is ignored

### ISSUE THREAD

**Issue by jxns** [contao/contao#2670]
**Affected version(s)**

Contao 4.10.5

**Description**

I tried to adjust the sessionTime for logged in members. I configured the sessionTimeout in my /config/config.yml:

```
contao:
    url_suffix: ''
    localconfig:
        sessionTimeout: 28800
```

In PHP, the session.cookie_lifetime is set to 0 and the session.gc_maxlifetime is set to 7200.
I also cleared the cache via the Contao Manager.
Nevertheless, I am automatically logged out after ~30 Minutes.

Any suggestions?

**Comment by aschempp** [comment]
Can you check the lifetime of your PHP session cookie in the browser?

**Comment by jxns** [comment]
Do you mean the "Expires / Max-Age"-Value of the "PHPSESSID"-Cookie? This is set to "Session".

**Comment by jxns** [comment]
Any suggestions?

**Comment by aschempp** [comment]
are you logged out of Contao or the Contao Manager?

**Comment by jxns** [comment]
Yes, I am only logged in to the frontend.

**Comment by jxns** [comment]
Do you have an idea what could cause this problem?

**Comment by leofeyer** [comment]
Maybe you also have to adjust the `cookie_lifetime` parameter of the Symfony framework bundle?

```yml
framework:
    session:
        cookie_lifetime: 28800
```
