### ISSUE TITLE
Main heading in the backend is cut off at the bottom

### ISSUE THREAD

**Issue by rabauss** [contao/contao#2686]
**Affected version(s)**

Contao 4.9+

**Description**

Unfortunately, since https://github.com/contao/contao/pull/2655 the line height is to low with overflow and the main heading in the backend is cut off at the bottom - see:
![image](https://user-images.githubusercontent.com/14016098/105688676-2d503c00-5efa-11eb-9f9a-8d376623bbaa.png)

**Comment by leofeyer** [comment]
Can you please check if the following CSS fixes the issue for you:

```css
#main_headline {
    margin: 18px 0;
}
#main_headline span {
    line-height: 20px;
}
```

**Comment by rabauss** [comment]
Not completely in the demo.contao.org it looks like this:

![image](https://user-images.githubusercontent.com/14016098/105696534-c2a3fe00-5f03-11eb-935c-bcef8bca00a7.png)

To reach nearly the state before 4.9.11 I think it should be:
```css
#main_headline {
    margin: 16px 0;
}
#main_headline span {
    line-height: 24px;
}
```
