### ISSUE TITLE
DSN Notation für Mailer Transports akzeptiert nur ein URL-codiertes Zeichen

### ISSUE THREAD

**Issue by de-es** [contao/contao#2705]
**Affected version(s)**

Contao 4.10.6

**Description**

Wenn ich in der `config/config.yml` Folgendes konfiguriere, erhalte ich beim löschen des Caches einen Fehler.

```
framework:
    mailer:
        transports:
            application: smtps://user@mail.de:xxx%2Fxxx%29xxx@smtpserver.de
```
führt zu

`You have requested a non-existent parameter "2Fxxx".`

```
application: smtps://user@mail.de:xxx%2Fxxx@smtpserver.de
```
funktioniert dagegen ohne Probleme.

Ab dem zweiten URL-encodierten Zeichen klappt es nicht mehr. Dabei ist es nicht erheblich, ob das Zeichen nur im Passwort vorkommt oder ob ich zB das `@` im Username schon encodiere.

Wenn ich einen kompletten DSN-String - mit mehreren codierten Zeichen - direkt im Environment mit MAILER_DSN setze, funktioniert es einwandfrei.
