### ISSUE TITLE
Concept paper: Frontend themes

### ISSUE THREAD

**Issue by richardhj** [contao/contao#2781]
<p align="center"><em>Draft Paper</em></p>

Proposing a new way to configure <br>Contao Themes
================

Current problems
----------------

Frontend themes in Contao heavily rely on the database. They cannot be git-tracked.

New Proposal
------------

Themes can be provided by adding a new folder `/themes/foobar` (alternatively `/contao/themes/foobar`, up for discussion).

<img width="562" alt="Screenshot 2021-02-20 at 22 08 29" src="https://user-images.githubusercontent.com/1284725/108608937-a7c18e00-73ca-11eb-8382-bae859011886.png">

The theme folder will contain a `theme.yml` file with all configuration.

```yml
# themes/my_theme/theme.yml

theme:
  title: My cool theme
  author: It's meee
  screenshot: files/my_files/screenshot.png

  layouts:
    # "_default" is a special key.
    # Will create a "default" layout and all other layouts will merge these settings.
    # Using this key is optional.
    _default:
      title: Default layout
      template: fe_page
      rows: 3rw
      sections:
        before:
          - section1
        bottom:
          - section2

    other_layout:
      title: Other layout
      encore_entrypoint: other

  image_sizes:
    # Same config as for global config? Or is this setting superfluous?
```

You can define the sections, rows, and cols of the layout, but you don't need to for simple layouts and just use twig includes. When using sections, those can be accessed by the `block('bottom')` function.

The theme will show up in the backend as all other themes. However, some operations are disabled: It won't be possible
to edit and delete the theme, nor to edit a theme's css files. Nevertheless, the modules can be configured as is.

For the layouts, the layouts will be predefined as they are defined in the `theme.yml` (you cannot create new layouts
in the backend, they must be defined in the `theme.yml`). The edit mask for layouts is way shorter. You only need to
configure the included modules per layout. 

### Asset handling

The "public" folder inside a themes' folder (see screenshot) will automatically be symlinked to the "web/themes/my_theme" folder.
We leverage Symfony Encore and make use of the [`entrypoints.json`](https://symfony.com/doc/current/frontend/encore/simple-example.html#configuring-encore-webpack).
The entrypoint, –that is defined in the `webpack.config.js`–, will be configured per layout in the `theme.yml` (see above).

Exemplary `webpack.config.js` file (using Encore should stay optional)

```js
const Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('public')
    .setPublicPath('/themes/my_theme')
    .setManifestKeyPrefix('')

    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .disableSingleRuntimeChunk()

    .addEntry('app', 'assets/scripts/app.js')
    .addEntry('other', 'assets/scripts/other.js')
    .enablePostCssLoader()
;

module.exports = Encore.getWebpackConfig();
```

Alternatively to the Encore approach, it shall be possible to define the CSS and JS files in the `theme.yml` under the layout section.

How to distribute themes
------------------------

Themes can be distributed as a Composer package.

```json
{
  "name": "acme/my_theme",
  "type": "contao-theme"
}
```

The Contao Manager plugin will copy (not a symlink) the contents of the folder "assets" inside the package to the `themes/my_theme` directory.
This way, themes can add dependent Composer packages, i.e. extensions.

______

*This is a working paper. Up for discussion. Issue description will be updated.*
