### ISSUE TITLE
Detect old database setup

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#285]
The changes from https://github.com/contao/contao/commit/51134b52ccef0140417b2d3ab827ff91b00741cf need to be re-added (and adjusted) to prevent the issue from #282. If the MySQL version is lower than 5.7.7, there are only two options to run Contao:

- Enable large prefixes
- Use MyISAM and utf8

**Comment by fritzmg** [comment]
Agreed. Why was it removed in the first place?

**Comment by leofeyer** [comment]
Silly me…

**Comment by leofeyer** [comment]
Re-added in e8d634947be528585c72aac9281b2f9c9d3581c3. I have also extended the unit tests to check different database versions.

**Comment by fritzmg** [comment]
Since you re-added the variable index length depending on the database configuration, is the message in the install tool still strictly necessary?

**Comment by leofeyer** [comment]
What exactly do you mean?

**Comment by fritzmg** [comment]
May be I am misunderstanding this, but the main problem of #282 was the too long index length, that Contao wanted to create. In e8d6349 you have made some changes to `getDefaultIndexLength` - I am assuming this would actually fix it, without setting
```
innodb_large_prefix = 1
innodb_file_format = Barracuda
innodb_file_per_table = 1
```
or
```
doctrine:
    dbal:
        connections:
            default:
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                    engine: MyISAM
```
?
