### ISSUE TITLE
Use a separate channel for Contao deprecations

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2886]
![](https://user-images.githubusercontent.com/1192057/111491685-5c39a000-873c-11eb-98e3-3b94e5f24a9a.png)

As you see, there is a way to specify a channel for deprecations. We should probably do this for Contao deprecations, so people can easily see what they need to update in their extensions. @contao/developers WDYT?

```yml
monolog:
    handlers:
        deprecation_stream:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-deprecations.log"

        deprecation_filter:
            type: filter
            handler: deprecation_stream
            max_level: info
            channels: ["php"] # <-- Here is where you can select which channels you want to log
```
