### ISSUE TITLE
Headlines in back end can get cut off

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2920]
**Affected version(s)**

Contao 4.9.13+

**Description**

Unfortunately the changes from #2875 introduced another issue 🙈 . The `<span>` parts in the back end headlines are now getting cut off instead of showing ellipsis:

Contao 4.9.12:

![c4912](https://user-images.githubusercontent.com/4970961/112725690-70865580-8f11-11eb-91fb-d333f0e38e64.png)

Contao 4.9.13:

![c4913](https://user-images.githubusercontent.com/4970961/112725692-74b27300-8f11-11eb-983e-b853cc240740.png)

**Comment by leofeyer** [comment]
Oh boy. 🙈 Can you please revert `display: inline-flex;` to `display: inline-block;` and add the following CSS definition:

```css
#main_headline * {
    vertical-align: text-top;
}
```

Does it fix the issue for you?

**Comment by fritzmg** [comment]
Hm, no that will still show the `>` too low. Only with `vertical-align: top` would the arrow look correctly aligned with the text.

Instead of relying on `inline-block` or `inline-flex`, we could remove ` › ` from the HTML output and do the following:

```css
#main_headline {
    display: flex;
    flex-wrap: wrap;
}

#main_headline span {
    display: block;
}

#main_headline span + span:before {
    content: '›';
    margin: 0 0.4em;
}
```

Then the arrow will be part of the regular text and always be aligned correctly. Alternatively just doing

```css
#main_headline span {
    display: inline-block;
}

#main_headline span + span:before {
    content: '›';
    margin: 0 0.4em;
}
```

will work as well of course.

**Comment by leofeyer** [comment]
That seems to be the best solution. 👍🏻 To make it look like before, I had to slightly modify your CSS:

```css
#main_headline span {
    display: inline-block;
}

#main_headline span + span::before {
    content: '›';
    margin: 0 0.25em;
    font-weight: normal;
}
```

Does this work for you as well?

**Comment by fritzmg** [comment]
Shouldn't the arrow be `font-weight: 600`? That's what it would be as a regular character within `#main_headline`.

Also you might want to keep whitespace between `</span> <span>` for screen readers, I think. The `0.25em` are not quite pixel perfect in relation to the space before, at least in my case - but we could just add the spaces to the `content` definition. Then the CSS would be:

```css
#main_headline span {
    display: inline-block;
}

#main_headline span + span::before {
    content: '› ';
    font-weight: 600;
}
```

Note: the `inline-block` causes the `#main_headline` to be almost 2 Pixel larger than the `inline-flex` version.
