### ISSUE TITLE
Deprecate/remove characterSet config option

### ISSUE THREAD

**Issue by ausi** [contao/contao#3050]
As discussed in https://github.com/contao/contao/pull/3014#discussion_r643119966 the characterEncoding should always be `utf-8`.

**Comment by ausi** [comment]
I just tried to use a different charset with the following config:

```yaml
contao:
    localconfig:
        characterSet: iso-8859-1
doctrine:
    dbal:
        connections:
            default:
                default_table_options:
                    charset: latin1
                    collate: latin1_general_ci
```

I was not able to save fields that included a non-ASCII character. Correctly stored characters from the database were not displayed correctly in the frontend.

As our translations are in UTF-8 they don’t work either. Chinese looks like this for example:
<img width="562" alt="Bildschirmfoto 2021-06-04 um 15 09 25" src="https://user-images.githubusercontent.com/367169/120806596-57b8a280-c547-11eb-9169-112be18bb91f.png">

I highly doubt that there is a Contao 4 installation out there that does not use `utf-8` as the `characterSet`.

Therefore we can safely deprecate this option IMO.
