### ISSUE TITLE
Config wird nicht akzeipiert

### ISSUE THREAD

**Issue by katgirl** [contao/contao#3357]
**Affected version(s)**

Contao 4.12

**Description**

Bei folgender Konfiguration

```bash
user@host:/www/htdocs/user/domain.ltd$ cat config/config.yml 
# Contao configuration
contao:
  legacy_routing: false
  localconfig:
    adminEmail: 'webmaster@domain.ltd'
    timeZone: Europe/Berlin
    timeFormat: H:i
    dateFormat: d.m.Y
    datimFormat: d.m.Y H:i
    undoPeriod: 5184000
    imageWidth: 3000
    imageHeight: 3000
    maxFileSize: 20480000
    minPasswordLength: 12
    folderUrl: true
    licenseAccepted: true
    installPassword: Installpassword
doctrine:
  dbal:
    connections:
      default:
        options:
          1002: "SET SESSION sql_mode=(SELECT CONCAT(@@sql_mode, ',TRADITIONAL'))"
user@host:/www/htdocs/user/domain.ltd$ cat system/config/localconfig.php 
<?php
// Ansible managed

### INSTALL SCRIPT START ###
$GLOBALS['TL_CONFIG']['websiteTitle'] = 'Titel der Webseite';
$GLOBALS['TL_CONFIG']['minifyMarkup'] = true;
$GLOBALS['TL_CONFIG']['gzipScripts']  = true;
### INSTALL SCRIPT STOP ###
```

Wird beim Seitenaufruf egal ob Frontend oder Backend auf das Installtool weitergeleitet um die Lizenz zu akzeptieren.

setze ich in die ```localconfig.php```
```php
$GLOBALS['TL_CONFIG']['licenseAccepted'] = true;
```
ein geht es ohne Probleme.

**Comment by fritzmg** [comment]
I cannot reproduce. Setting `contao.localconfig.licenseAccepted` still works fine in Contao 4.12.

**Comment by ausi** [comment]
Did you clear the cache after changing the config?

**Comment by katgirl** [comment]
Das hängt damit zusammen, wenn die folgenden Zeilen in der Config fehlen:

```yaml
doctrine:
  dbal:
    connections:
      default:
        options:
          1002: "SET SESSION sql_mode=(SELECT CONCAT(@@sql_mode, ',TRADITIONAL'))"
```
und es benötigt wird. Es ist bei uns auch nur bei All-Inkl aufgetreten. Inzwischen musste ich auch feststellen, das keine der Konfigurationen aus ```contao.localconfig``` gezogen werden. Die anderen Einstellungen aus der ```config.yaml``` werden aber umgesetzt.

Auf unserem Test-Server klappt es auch. Ja der Cache wird jedes mal beim schreiben der Configs oder bei Updates/Upgrades geleert.

**Comment by fritzmg** [comment]
> Das hängt damit zusammen, wenn die folgenden Zeilen in der Config fehlen:

I also cannot reproduce that. `contao.localconfig.licenseAccepted` works regardless of whether any doctrine configuration is present or not.

**Comment by katgirl** [comment]
Hier mal ein Video das zweigt was ich da mache: https://www.awesomescreenshot.com/video/4934124?key=306a1d5b359f1d63e3a5fe1cc151681c 

System
```bash
PHP 7.4.22 (cli) (built: Jul 30 2021 13:08:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.22, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

Composer.json
```json
{
    "type": "project",
    "require": {
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "4.12.*",
        "erdmannfreunde/contao-grid-bundle": "^1.0",
        "erdmannfreunde/euf_nutshell": "^1.1",
        "erdmannfreunde/theme-toolbox": "^1.0",
        "inszenium/inszenium-theme-bundle": "^1.0",
        "terminal42/notification_center": "^1.5"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by fritzmg** [comment]
Can you debug which values are present in `$config['localconfig']` here, when the container is built:

https://github.com/contao/contao/blob/f1b3c56856666c38fe080fd04e00797b8fbed310/core-bundle/src/DependencyInjection/ContaoCoreExtension.php#L82

?

**Comment by fritzmg** [comment]
@katgirl something in your setup is overwriting `contao.localconfig`. In your video you say, that you only see the default values, however that is not actually true. Your video shows the following output for `debug:config contao`:

```yaml
contao:
    localconfig:
        folderUrl: true
```

That is _not_ the default config. The default config when running `debug:config contao` would not include any `contao.localconfig` values at all.

**Comment by katgirl** [comment]
Hier die Ausgabe:
```
inszenium@webgate:~/html/detaulttheme.inszenium.cloud$ php vendor/bin/contao-console debug:config contao
array(1) {
  ["folderUrl"]=>
  bool(true)
}
array(1) {
  ["folderUrl"]=>
  bool(true)
}
array(1) {
  ["folderUrl"]=>
  bool(true)
}

Current configuration for extension with alias "contao"
=======================================================

contao:
    preview_script: /preview.php
    pretty_error_screens: true
    legacy_routing: true
    localconfig:
        folderUrl: true
    mailer:
        transports:
            kirsten_roschanski.de:
                from: null
    csrf_cookie_prefix: csrf_
    csrf_token_name: contao_csrf_token
    encryption_key: '%kernel.secret%'
    error_level: 8183
    intl:
        locales: {  }
        enabled_locales: {  }
        countries: {  }
    locales: {  }
    prepend_locale: false
    upload_path: files
    editable_files: 'css,csv,html,ini,js,json,less,md,scss,svg,svgz,txt,xliff,xml,yml,yaml'
    url_suffix: .html
    web_dir: /var/customers/webs/inszenium/detaulttheme.inszenium.cloud/web
    image:
        bypass_cache: false
        imagine_options:
            jpeg_quality: 80
            jpeg_sampling_factors:
                - 2
                - 1
                - 1
            interlace: plane
        imagine_service: null
        reject_large_uploads: false
        sizes: {  }
        target_dir: /var/customers/webs/inszenium/detaulttheme.inszenium.cloud/assets/images
        target_path: null
        valid_extensions:
            - jpg
            - jpeg
            - gif
            - png
            - tif
            - tiff
            - bmp
            - svg
            - svgz
            - webp
    security:
        two_factor:
            enforce_backend: false
    search:
        default_indexer:
            enable: true
        index_protected: false
        listener:
            index: true
            delete: true
    crawl:
        additional_uris: {  }
        default_http_client_options: {  }
    backend:
        attributes: {  }
        custom_css: {  }
        custom_js: {  }
        badge_title: ''
```

Danke für den Tip habe den Fehler gedunden, der ist im Theme: 
https://github.com/erdmannfreunde/optimist-theme-bundle/blob/master/src/ContaoManager/Plugin.php#L21
