### ISSUE TITLE
Improve back end badge readability

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3371]
Warning: this is highly opinionated. :smile: 

I am now using our new shiny back end badges and I really like them! I feel their appearance could be improved by increasing the padding and maybe using less font weight, though. Right now they look a bit off and are a bit hard to read compared to the rest of the back end design.

![Screenshot_20210823_222427](https://user-images.githubusercontent.com/5305677/130514432-e67c70f2-6ccb-49c7-85bf-6b8963a67bb2.png)

Maybe something like this?

![Screenshot_20210823_222240](https://user-images.githubusercontent.com/5305677/130514223-f2f20fcb-737a-460e-8fbe-dd51ffafc569.png)

```css
.badge-title {
    float: right;
    margin-left: 8px;
    margin-top: -6px; /* adjusted */
    border-radius: 1em; /* adjusted */
    padding: 5px 7px; /* adjusted */
    background: #0f1c26;
    color: #fff;
    font-size: .75rem;
    font-weight: 400; /* adjusted */
}
```

/cc @rabauss  Wdyt? :grimacing:
