### ISSUE TITLE
TemplateLocator queries database even if not fully installed

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3557]
**Affected version(s)**

Contao 4.12

**Description**

The `TemplateLocator::findThemeDirectories()` tries to find all themes even if the Contao installation has not been fully installed.

<img width="627" alt="" src="https://user-images.githubusercontent.com/1192057/136358414-3b784cd7-5848-4b5d-ae11-54dd48ac7ad9.png">

You can reproduce this with `composer create-project contao/managed-edition contao 4.12` on the command line.

@m-vo How do we fix this? By catching more exceptions in the try-catch block?

**Comment by leofeyer** [comment]
Here is a workaround until the fix is ready:

Install without scripts:

* `composer create-project contao/managed-edition contao 4.12 --no-scripts`

Manually add the `parameters.yml` file:

* `mkdir config`
* `vi config/parameters.yml`

```yml
parameters:
    database_host: localhost
    database_port: 3306
    database_user: <db_user>
    database_password: <db_passwd>
    database_name: <db_name>
```

Run the Composer scripts:

`composer run post-install-cmd`
