### ISSUE TITLE
Hook loadDataContainer no security user

### ISSUE THREAD

**Issue by baumannsven** [contao/contao#3697]
**Affected version(s)**

Contao 4.9

**Description**

In the loadDataContainer hook I don't get a user from security.

services.yml
```yaml
services:
  App\Security\AppSecurity:
      arguments:
        - '@Symfony\Component\Security\Core\Security'
      tags:
        - name: contao.hook
          hook: loadDataContainer
```
