### ISSUE TITLE
Back end styling issue with article records

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3700]
**Affected version(s)**

Contao 4.9, 4.12, 4.x

**Description**

Currently there is a styling issue in the back end for articles in the back end:

![image](https://user-images.githubusercontent.com/4970961/142396319-14cf1d20-2c89-4f8e-83f4-1eb86d1cf7aa.png)

May be removing the style for `.tl_tree_xtnd .tl_file .tl_left a` and then setting 

```css
.tl_left > a:last-of-type {
    vertical-align: text-bottom;
}
```

can solve the issue. In 4.12 it needs to be

```css
.tl_left > * {
    vertical-align: text-bottom;
}
```

Not sure if that is the best approach though.
