### ISSUE TITLE
Improve the "copy to clipboard" feature

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4147]
### Description

As discussed in #4133, we need a visual confirmation if someone copies a preview link to their clipboard. The confirmation must not be permanent and must not require to be closed manually. It could be either a flash message or an inline confirmation.

![](https://user-images.githubusercontent.com/1192057/154438692-4085e6e2-bc65-4dd1-ab81-4217cf36162a.png)

While we are on this, we might also merge the `clipboard.js` script into the `core.js` script to save one HTTP request.

**Comment by aschempp** [comment]
> While we are on this, we might also merge the clipboard.js script into the core.js script to save one HTTP request.

I think we should split the features into separate files, and saving the request is a no-brainer with HTTP/2. Also, we don't need to load the script on 99% of the pages, only if a user has access to and accesses the preview link backend. 🙃

**Comment by aschempp** [comment]
I'm happy to implement this using https://www.stimulus-components.com/docs/stimulus-clipboard once we have #5406 😎

**Comment by m-vo** [comment]
I already implemented this as a stimulus controller + some CSS magic for my file manager prototype. Can contribute this 👍

**Comment by m-vo** [comment]
[copytoclipboard.webm](https://user-images.githubusercontent.com/5305677/202914055-6e16a282-3878-4b37-95c1-6223a8ded1e6.webm)

When clicking three things happen:
1) the clipboard content is set
2) a CSS class is added to the element, which makes the icon change and plays a single shot animation (here: the green flash); if the class is already there, it is removed first, so that the animation is played again
3) all other instances are notified to remove the class

Pseudocode:
```twig
<i class="clipboard" {{ stimulus_controller('contao/clipboard-copy', [], {'copied': 'clipboard--copied'}) }}>
    the-thing-that-is-copied
</i>
```

```css
.clipboard {
    &:before {
        background-image: url("…");
    }

    &--copied {
        animation: flash 2 alternate 500ms;

        &:before {
            background-image: url("…");
        }
    }

    @keyframes flash {
        0% {}
        80% {background-color: green;}
        100% {background-color: green;}
    }
}
```


Wdyt?
