### ISSUE TITLE
Lazy Services

### ISSUE THREAD

**Issue by ausi** [contao/contao#4154]
As discussed in Slack, #4151 was a quickfix to make the Contao Manager work with Contao 4.13.0.

We should discuss if we want to keep the `lazy: true` there and therefore use `lazy: true` for other things as well in the future, or if we should go with a different solution instead (and decide to never use `lazy: true`).

What I don’t like about proxy classes is, that they are not visible to the developer who is using them. Writing code like the following will not work as expected if the service is lazy:

```php
function doSomethingRisky(MyService $myService) {
	try {
		$myService->somethingRisky();
	} catch (\Throwable $exception) {
		return false;
	}
	
	return true;
}
```

Such a lazy feature needs to be visible to the developer IMO.  
In an optimal world this would look like this:

```php
function doSomethingRisky(Lazy<MyService> $myServiceProxy) {
	$myService = $myServiceProxy->get();
	
	try {
		$myService->somethingRisky();
	} catch (\Throwable $exception) {
		return false;
	}
	
	return true;
}
```

Currently possible would be something like this:

```php
function doSomethingRisky(MyService&LazyLoadingInterface $myService) {
	$myService->initializeProxy();
	
	try {
		$myService->somethingRisky();
	} catch (\Throwable $exception) {
		return false;
	}
	
	return true;
}
```

**Comment by ausi** [comment]
Searching through Symfony I think Service Closures match best what we want to achieve:

```yaml
contao.listener.command_scheduler:
    //...
    arguments:
        - !service_closure '@contao.cron'
        //...
```

```php
/**
 * @param callable(): Cron $cronLazy
 */
function __construct(\Closure $cronLazy, …) {
	$cron = $cronLazy();
	$cron->run();
	// OR
	$cronLazy()->run();
}
```

**Comment by fritzmg** [comment]
But then you would need to have prior knowledge about the service that you are trying to inject. Whereas with `lazy: true` you don't have to worry about that at all. From a DX point of view I do not want to have to know that some services should be injected lazily and some do not - and I do not want to need to take care of that myself.

**Comment by m-vo** [comment]
> But then you would need to have prior knowledge about the service that you are trying to inject. Whereas with lazy: true you don't have to worry about that at all. 

That's exactly the point. For DI it's crucial to know if you're working with a future of an object or an object. IMHO using transparent ghost objects is not bad in general, but for this scenario it's a very bad design pattern.

**Comment by ausi** [comment]
> But then you would need to have prior knowledge about the service that you are trying to inject.

This can (and IMO should) be solved by making the dependencies of `contao.cron` themself lazy. Should be easily done like so:

```yaml
contao.cron:
    class: Contao\CoreBundle\Cron\Cron
    public: true
    arguments:
        - !service_closure '@contao.repository.cron_job'
        - !service_closure '@doctrine.orm.entity_manager'
        - '@?logger'
```

This has basically the same affect as the current `lazy: true` but without “magic” objects that get handed to the developers.
