### ISSUE TITLE
Truncation Breadcrumb Elements

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4169]
### Affected version(s)

4.13.0

### Description

Breadcrumb elements are truncated without need.

E. g. "Templates › templates/analytics_goo..." instead of "Templates › templates/analytics_google.html5" in older versions.

**Comment by fritzmg** [comment]
> Breadcrumb elements are truncated without need.

Why do you think so? They need to be truncated, otherwise the will get too long.

**Comment by ausi** [comment]
I think we could use CSS like this one:

```
#main_headline {
  display: flex;
}
#main_headline span {
  max-width: none;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
#main_headline span:last-of-type {
  flex-shrink: 0;
}
#main_headline span + span::before {
  content: "\A0› ";
}
```

This way, if all elements fit, no text gets truncated.

**Comment by leofeyer** [comment]
I tried using flexbox, too, however, this is why I haven‘t implemented it:

<img width="1028" alt="" src="https://user-images.githubusercontent.com/1192057/158220727-193cdef9-48ac-45fe-a002-d9bca231b364.png">

With your changes:

<img width="1029" alt="" src="https://user-images.githubusercontent.com/1192057/158220761-3464dfa9-eb07-4963-8233-76695857ef01.png">

Ideally, the browser should only shorten the long items. 🙈 Maybe we can add a `min-width` to improve the default behavior?

**Comment by ausi** [comment]
> Ideally, the browser should only shorten the long items.

Like so?

```css
#main_headline {
  display: flex;
}
#main_headline span {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: max-content;
  flex-grow: 1;
  flex-shrink: 0;
  flex-basis: 0;
}
#main_headline span + span::before {
  content: "\A0› ";
}
```
