### ISSUE TITLE
Cannot set additional headers for crawler

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4387]
### Affected version(s)

4.9, 4.13, 5.x

### Description

Currently it is only possible to set additional [HTTP Client Options](https://symfony.com/doc/current/reference/configuration/framework.html#reference-http-client) that are scalars. But you cannot set options that are arrays, like additional headers. For instance, the following will not work:

```yaml
contao:
    crawl:
        default_http_client_options:
            headers:
                'User-Agent': 'Firefox'
```

The error will be:

```
Invalid type for path "contao.crawl.default_http_client_options.headers". Expected "scalar", but got "array".
```

I think we should probably allow "everything" there? Or should we copy the configuration tree of the Symfony Framework Bundle?

/cc @Toflar
