### ISSUE TITLE
Add class to .ce_player if it has video or audio

### ISSUE THREAD

**Issue by Aybee** [contao/contao#441]
**Description**  
Wäre es möglich dem `div.ce_player` entsprechend des Inhalts die Klassen `video` bzw. `audio` zu vergeben?

**Example** 
Der Wrapper für ein Video wird meist responsive gestaltet und benötigt daher z.B. so ein CSS
```css
.ce_player.video {
  position: relative;
  padding-bottom: 56.25%;
}
.ce_player video {
  position: absolute;
  top: 0;
  bottom: 0;
  margin: auto;
  max-width: 100%;
  height: auto;
}
```
Momentan suche ich nach `video`s innerhalb von `.ce_player` und gebe dem `parent `die Klasse `video`
```js
$('video').parent('.ce_player').addClass('video');
$('audio').parent('.ce_player').addClass('audio');
```
