### ISSUE TITLE
Database connection using environment variables leads to "Malformed url"

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4546]
### Affected version(s)

> 4.13

### Description

First of all I'm not sure if this issue is related to Contao at all. Could be that Symfony or Doctrine is to blame here.

We've updated a customers installation to 4.13 which is located in a Docker container on an AWS environment. After doing so a `composer install` fails with

![image](https://user-images.githubusercontent.com/226890/165072745-bcc860a7-c740-408c-8e19-3c2d0e1642b4.png)

I've added a debug printing in the `DriverManager.php` which shows that the environment variables are not resolved correctly (except the hostname?):

```
benny@devel:~/www/something$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating autoload files
98 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
> @php vendor/bin/contao-setup
 ------------------------------
pdo-mysql://%25env%28MYSQL_USER%29%25:%25env%28MYSQL_PASSWORD%29%25@127.0.0.1:0/%25env%28MYSQL_DATABASE%29%25 
------------------------------

In DriverManager.php line 314:

  Malformed parameter "url".


Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 1
```

This is the contents of the `parameters.yml`

```
# This file has been auto-generated during installation
parameters:
    database_host: '%env(MYSQL_HOST)%'
    database_port: '%env(MYSQL_PORT)%'
    database_user: '%env(MYSQL_USER)%'
    database_password: '%env(MYSQL_PASSWORD)%'
    database_name: '%env(MYSQL_DATABASE)%'
    secret: redacted
```

And this is the `.env` file I used for testing:

```
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3308
MYSQL_USER=root
MYSQL_PASSWORD=
MYSQL_NAME=something
```
All of this has worked prior to updating to 4.13.
