### ISSUE TITLE
Remove imagemargin and floating in Contao 5

### ISSUE THREAD

**Issue by bezin** [contao/contao#4575]
### Description

Many years ago we had `margin before` and `margin after` fields for content elements (not exactly sure about that), which we removed because that was theme-related. I think we should finally remove `imagemargin` and `floating`, too, as this is theme-related as well and should be solved otherwise.

The same goes for the layout options (rows and columns) in the gallery element actually, but this might be another topic.

**Comment by fritzmg** [comment]
Why do you want to remove floating? We use that all the time. Same with images per row for gallery elements.

**Comment by bezin** [comment]
> Why do you want to remove floating? We use that all the time. Same with images per row for gallery elements.

We don't use either. But I can see, how you might use these — at least floating.

Let us see, how others use these settings.

**Comment by leofeyer** [comment]
I agree that we should probably keep the floating setting.

**Comment by fritzmg** [comment]
And regarding the row setting for gallery elements - that's how we use it:

```scss
.ce_gallery {
    ul {
        display: grid;
        gap: var(--grid-gap);
    }

    @for $i from 1 through 12 {
        ul.cols_#{$i} {
            grid-template-columns: repeat(#{$i}, 1fr);
        }
    }
}
```

plus a mechanism to automatically set the appropriate image size from `contao.image.sizes`.
