### ISSUE TITLE
Preview bar broken if empty backend parameters in config.xml

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#4630]
### Affected version(s)

4.13.4

### Description

Acutally i had two similar installations. On the PROD site the Preview bar was broken after updating to 4.13.4. On DEV site everything was fine. After rerolling to 4.12.7 the error occured here too.

<img width="587" alt="Bildschirmfoto 2022-05-06 um 09 27 43" src="https://user-images.githubusercontent.com/6390770/167295812-0a0b0d81-7d6b-4422-a1ff-ba7e558c9a85.png">
<img width="503" alt="Dev Konsole" src="https://user-images.githubusercontent.com/6390770/167295893-8593ef7c-8c84-404d-b8ab-da09ffd78aa8.png">

I figured out the reason of this problem. Empty backend parmeters in config.yml turned out to be the problem:

**DEV**
```
backend:
        attributes:
            app-name: JBZ Testserver
        badge_title: JBZ Testserver
        custom_css:
            - files/backend/custom.css

```

**PROD**
```
  backend:
        attributes:
            app-name:
        badge_title:
        custom_css:
            - files/backend/custom.css
```

After removing empty lines "attributes, app-name, badge_title" everything is working fine again.

```
 backend:
        custom_css:
            - files/backend/custom.css
```

Topic Contao-Forum: https://community.contao.org/de/showthread.php?83068-quot-Error-while-loading-the-preview-bar-quot-Nach-Update-auf-4-13-4&p=558728&viewfull=1#post558728
