### ISSUE TITLE
Long main headline ruins the look of the UI

### ISSUE THREAD

**Issue by georgpreissl** [contao/contao#4771]
### Affected version(s)

4.13.4

### Description

When a long News-Title shows up in the main headline it ruins the look of the UI:
![Bildschirmfoto 2022-06-01 um 15 38 52](https://user-images.githubusercontent.com/4385048/171419309-cfbb6987-b0c7-4bc4-8ffe-96c8e2c46a18.png)

Of course, the full-surface user interface can be selected to circumvent the problem. However, I think it should still be possible to use the standard UI with long news titles.

**Comment by ausi** [comment]
Can you reproduce this issue on https://demo.contao.org/ ?
Which browser and browser version are you using?

**Comment by asaage** [comment]
That must be a bug of your BE-Theme.
I can not confirm this - there is
```css
 #main_headline span {
   ...
   white-space: nowrap;
   overflow: hidden;
   text-overflow: ellipsis;
   ...
}
```
in place which has good browser-support
