### ISSUE TITLE
Optimize Installtool appearance for database updates

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4890]
### Affected version(s)

4.13.5

### Description

I have installed a new extension. There are accordingly new database updates in the Installtool.

This leads partly to an incorrect layout. See screenshot.
![screen-20220628_5ForkXaA](https://user-images.githubusercontent.com/23719181/176150869-bed7ecf5-5790-45e0-adc5-9eeb811ee550.jpg)

**Comment by ausi** [comment]
This can probably be fixed by adding:

```css
fieldset.tl_tbox, fieldset.tl_box {
    min-width: 0;
}
```

@contaoacademy is Contao 4.9 affected too?
