### ISSUE TITLE
Database configuration errors missing from contao:migrate

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4970]
### Affected version(s)

4.9, 4.13

### Description

The Contao Install Tool currently executes a few checks for the current database configuration and shows an error and what you will need to do, if applicable. These checks are missing from `contao:migrate` currently.

For example, if you configure something like:

```yaml
# config/config.yaml
doctrine:
    dbal:
        connections:
            default:
                default_table_options:
                    charset: utf8
                    collation: utf8_unicode_ci
```

but your database server does not support the `utf8` designation anymore (which is deprecated - it is now called `utf8mb3`), the install tool would usually tell you:

![image](https://user-images.githubusercontent.com/4970961/178235077-15cca519-9731-4a65-9e7e-50f7be55680b.png)

However, if you execute `contao:migrate --no-interaction` in such a case, it will run indefinitely, as it tries to convert `utf8mb3` to `utf8` over and over again.

I think we should add some of these checks to `contao:migrate` as well, at least the ones that can lead to a situation as mentioned instead of an exception.
