### ISSUE TITLE
Back end login password icon

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#5202]
### Affected version(s)

4.13.8

### Description

https://demo.contao.org/contao/login

![backend](https://user-images.githubusercontent.com/1942550/185441629-28dd077e-9404-4132-9a1b-152111251e67.png)

Replace 31px by 6px.

```css
label[for="password"], 
label[for="confirm"] {
        …
	right: 6px;
        …
}
```
