### ISSUE TITLE
Help wizard of "Image size" dropdown doesn't take into account predefined image sizes

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#5239]
### Affected version(s)

4.13

### Description

This is 3 small issues in one:

1. The docs never mention that text for the wizard is fetched from `MSC` domain, not from `translations/image_sizes.en.yml`. This belongs probably in contao/docs, I just mention it here for completeness.

2. In `BackendHelp.php` controller, array of predefined options comes in structured differently, than core options, and the label is being used instead of key, here:

https://github.com/contao/contao/blob/4fb1c1555fcac428cb42e66a22c8236dd3356ad0/core-bundle/src/Resources/contao/controllers/BackendHelp.php#L104-L107

3. In the code above, `null` is being stored as a row, which makes `be_help.html5` throw a warning in php 8:

```
ErrorException:
Warning: Trying to access array offset on value of type null

  at vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_help.html5:42
```

In production or in php 7.4, it just outputs empty rows:

![image](https://user-images.githubusercontent.com/10257912/187917639-2b750f2a-36e5-4a11-963c-1dc5c7616cc4.png)

**Comment by leofeyer** [comment]
How can I reproduce this issue?

**Comment by ameotoko** [comment]
Just configure an image size in `config.yml`:

```yaml
contao:
    image:
        sizes:
            video_placeholder:
                width: 1280
                resize_mode: proportional
                densities: '1x'
                formats:
                    jpg: [ webp, jpg ]
                    png: [ webp, png ]
```

I just overthought the issue's title 😅. Simply put, there seems to be no way to add a help text for these sizes to the wizard (despite the existing section for them, see screenshot).
