### ISSUE TITLE
Make collapsed elements in backend more useful

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#5397]
It turns out that users with motor impairments (like a spastic paralysis, for example) will have to do a very hard job if they want to see what's inside an collapsed element in backend, since the former green arrow button has been replaced with some sort of an ellipsis in Contao 4.

This ellipsis is very small, and users with a spastic paralysis won't manage to click on that at all. For illustration: Try to click that ellipsis with someone behind you, putting your arm backward and forward in random intervals. I promise, you won't hit the ellipses within the next 20 minutes or so.

To make things even worse, the only way to make content elements more usable for them is turning the shortening of elements completely off in system settings, working then for no user at all.

Furthermore, switching this setting has several major issues for the whole backend on site with lots of content (i.e. an article with very long texts, mixed contents with inline images, and more). In some cases, you will have to scroll through very long content, which makes working in backend some kind of painful and confusing.

I think, there are two possible solutions. First one could be moving the setting for collapsed elements into the backend user account so that everyone could decide whether to show the collapsed view or the full one.

Second (and ways more better) should be a fully functional replacement of the ellipsis with a bigger one or an icon again, probably with a combination of a setting per user. 

I would highly appreciate if Contao would be more accessible in backend, too.

**Comment by Toflar** [comment]
I understand, can you provide a proposal that would work for these people?

**Comment by asaage** [comment]
originaly related to https://github.com/contao/core-bundle/issues/1198

**Comment by kikmedia** [comment]
Beside the settings per user, the ellipsis is too small for users with impairments. All other icons have a minimal of 16px height, this one - regarding of backend zoom - starts at a line-height of 11px (for .limit_toggler) and an effective font size of 14px. As you can imagine, even in a 30px font size, three dots are too small.

I suggest a replacement with an icon which could be scaled like all the other ones. Maybe some sort of arrow, again?

**Comment by m-vo** [comment]
btw.: the 'uncollapse' is broken and also triggers an edit (tested in the Contao demo) - this should be fixed as well when potentially reworking this.

**Comment by m-vo** [comment]
I'm -1 for a user setting but +1 for a better solution like making the current ellipsis icon just a bit bigger (overlapping the content).

**Comment by dmolineus** [comment]
Imho a user setting would be useful for any user no matter if they have impairments. From my point of view iI don't see a reason why a user should not be allowed to choose the preferred setting.

**Comment by leofeyer** [comment]
Just so we are on the same page – you are talking about this:

<img width="787" alt="" src="https://user-images.githubusercontent.com/1192057/35063775-63b1b58c-fbc8-11e7-8d75-3955f3de48a6.png">

> I think, there are two possible solutions. First one could be moving the setting for collapsed elements into the backend user account so that everyone could decide whether to show the collapsed view or the full one.

Fine with me.

> Second (and ways more better) should be a fully functional replacement of the ellipsis with a bigger one or an icon again, probably with a combination of a setting per user.

I'm against this. We have just replaced the big icon with a small one for several reasons.

> Beside the settings per user, the ellipsis is too small for users with impairments. All other icons have a minimal of 16px height, this one - regarding of backend zoom - starts at a line-height of 11px (for .limit_toggler) and an effective font size of 14px. As you can imagine, even in a 30px font size, three dots are too small.

Reading articles in the back end preview is cumbersome – even without impairments –, because you have to expand every single content element. Therefore the toggle is an inferior UX element which does not serve a high purpose and thus it is not as big as other icons.

> btw.: the 'uncollapse' is broken and also triggers an edit (tested in the Contao demo) - this should be fixed as well when potentially reworking this.

Works like a charm on my system.

**Comment by Aybee** [comment]
@leofeyer If we want to keep it visual such small we can only enlargen the click sensitive area.

![contao-4-be-limit-toggler-03](https://user-images.githubusercontent.com/1143013/35189092-ddac2192-fe43-11e7-9d64-46d45a4bd5e9.png)

And also set it to the top so we're able to immediately close the preview without moving the mouse or searching for the ellipses to close it again.

Here the CSS (some lines can be removed, they are only in there to overwrite the current CSS)
```css
.limit_height {
  line-height: 1.35;
}
.limit_toggler {
  width: 40px;
  left: 0;
  right: 0;
  top: 1px;
  bottom: auto;
  margin: auto;
  background: transparent;
  outline: thin dotted;
}
.limit_height[style^="height"] + .limit_toggler {
  outline: 0;
}
.limit_height[style] + .limit_toggler:hover {
  outline: thin dotted;
}
.hover-div:hover .limit_toggler,
.hover-row:hover .limit_toggler {
  background-color: transparent !important;
}
.limit_toggler button {
  background: transparent;
  width: 40px;
  height: 40px;
}
.limit_toggler button::-moz-focus-inner,
.limit_toggler button:focus,
.limit_toggler button:active {
  border: 0;
  outline: 0 !important;
}
.limit_toggler button span {
  top: -14px;
}
```
