### ISSUE TITLE
You have requested a non-existent parameter

### ISSUE THREAD

**Issue by leon1995** [contao/contao#5596]
### Affected version(s)

4.13

### Description

```
framework:
    mailer:
        transports:
            application: smtps://mail%40mydomain.tld:passwordpart1%21passwordpart2@server.tld
```
results in the following error when clearing the cache with `vendor/bin/contao-console cache:clear --env=prod --no-warmup`
```
In ParameterBag.php line 93:
    You have requested a non-existent parameter "40mydomain.tld:passwordpart1".
```

**Comment by fritzmg** [comment]
In YAML configuration files you need to escape the `%` by adding another `%` in front of it. So:

```yaml
framework:
    mailer:
        transports:
            application: smtps://mail%%40mydomain.tld:passwordpart1%%21passwordpart2@server.tld
```

See also https://docs.contao.org/manual/en/system/settings/#different-e-mail-configurations-and-sender-addresses
