### ISSUE TITLE
Create database backups using Contao cronjob

### ISSUE THREAD

**Issue by richardhj** [contao/contao#5655]
### Description

We can think of providing an option to create a database backup using the Contao cronjob.

```yaml
# config/config.yml
contao:
    backup:
        cronjob: 'daily' # one of: daily, weekly, hourly, ...
```

If well received, I can PR this.

**Comment by rabauss** [comment]
The logic for the registration could be copied from my extension :-)
https://github.com/bwein-net/contao-database-backup/blob/9a800daab0d6baa2c767d0905b7f8be40cfcd5a5/src/DependencyInjection/BweinDatabaseBackupExtension.php#L33-L38

https://github.com/bwein-net/contao-database-backup/blob/9a800daab0d6baa2c767d0905b7f8be40cfcd5a5/src/Cron/BackupCron.php

**Comment by k-webdesign** [comment]
Would this only backup the database or all/special files as well? And can I exclude special tables (search index,...)?

**Comment by fritzmg** [comment]
@k-webdesign this would only be for the database. And you can already exclude tables. See

```
config:dump-reference contao backup
```
```yaml
# Default configuration for extension with alias: "contao" at path "backup"
backup:

    # These tables are ignored by default when creating and restoring backups.
    ignore_tables:

        # Defaults:
        - tl_crawl_queue
        - tl_log
        - tl_search
        - tl_search_index
        - tl_search_term

    # The maximum number of backups to keep. Use 0 to keep all the backups forever.
    keep_max:             5

    # The latest backup plus the oldest of every configured interval will be kept. Intervals have to be specified as documented in https://www.php.net/manual/en/dateinterval.construct.php without the P prefix.
    keep_intervals:

        # Defaults:
        - 1D
        - 7D
        - 14D
        - 1M
```
