### ISSUE TITLE
Accessibility: "Expand element" toggle button

### ISSUE THREAD

**Issue by spacefront** [contao/contao#6024]
### Description

The buttons for expanding content elements are too small and do not have a title.

Current state:

![image](https://user-images.githubusercontent.com/6522818/236667314-f8fd43a5-cdaf-4707-ac45-4072c617d0fb.png)

Accessible size:

![image](https://user-images.githubusercontent.com/6522818/236667319-cef4f2dd-3e9b-4721-8b05-95109f19a041.png)

**Comment by k-webdesign** [comment]
An additional text would be helpful, too. Just like „expand all“ next to the icon

**Comment by zonky2** [comment]
As discussed on Contao Camp 2023 / https://github.com/contao-community-alliance/contao-camps/blob/main/2023/camp-2023.md#samstag-06052023

**Comment by aschempp** [comment]
I have added a title to the button in https://github.com/contao/contao/pull/6045, but we still need to discuss the appearance

**Comment by Aybee** [comment]
I have an old CSS for it. You can try it directly in Firefox Devtools. If you like the approach, I can optimize the CSS again (it's quite old). What's also special is that the button always stays in the same place so that you can close the preview directly and don't have to aim for the new position of the button after you opened the preview.
```css
.limit_height {
  padding-right: 70px;
}
.limit_height [class^=ce_] :last-child {
   margin-bottom: 0;
 }
.limit_toggler {
  width: 50px;
  height: 20px;
  left: 0;
  right: 0;
  top: 0;
  bottom: auto;
  margin: auto;
  background-color: rgba(0,0,0,.06);
  cursor: pointer;
}
.hover-div:hover .limit_toggler,
.hover-row:hover .limit_toggler {
  background-color: rgba(255,255,255,.9) !important;
}
.limit_toggler::after {
  content: '';
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  width: 3px;
  margin: auto;
  aspect-ratio: 1;
  background-color: #81A100;
  box-shadow: -8px 0 0 0 #81A100, 8px 0 0 0 #81A100;
  border-radius: 100%;
}
.limit_toggler button {
  width: 100%;
  height: 100%;
  background-color: transparent;
  display: block;
  overflow: hidden;
  position: relative;
  box-shadow: 0 -1px 0 0 transparent inset;
}
.limit_toggler button::before,
.limit_toggler button::after {
  content: '';
  position: absolute;
  width: 40px;
  aspect-ratio: 1;
  background: white;
  left: 0;
  top: 0;
  transform: rotate(60deg);
  transform-origin: 0 0;
  z-index: 999999;
}
.hover-div:hover .limit_toggler button,
.hover-row:hover .limit_toggler button {
  box-shadow: 0 -1px 0 0 rgba(0,0,0,.15) inset;
}
.hover-div:hover .limit_toggler button::before,
.hover-div:hover .limit_toggler button::after,
.hover-row:hover .limit_toggler button::before,
.hover-row:hover .limit_toggler button::after {
  border-top: 1px rgba(0,0,0,.15) solid;
}
.limit_toggler button::after {
  left: auto;
  right: 0;
  transform: rotate(-60deg);
  transform-origin: 100% 0;
}
.limit_toggler button span {
  display: none;
}
```
