### ISSUE TITLE
Can't select predefined image size

### ISSUE THREAD

**Issue by plandolt** [contao/contao#633]
**Affected version(s)**
4.8

**Description**  
After upgrding an existing installation from 4.7.x to 4.8.0 I tried the feature https://github.com/contao/contao/pull/537. But every time I try to select one of the "predefined" sizes I get this error:
![image](https://user-images.githubusercontent.com/922919/63104930-2771cf80-bf80-11e9-8895-424f23b670bd.png)

Here is my image size config:
```yaml
contao:
    url_suffix: ''
    image:
        sizes:
            angebotbox:
                name: 'angebot box'
                width: 530
                resizeMode: 'proportional'
                densities: '1x, 2x, 3x'
            angebotgalery:
                name: 'angebot gallery'
                width: 510
                resizeMode: 'proportional'
                densities: '1x, 2x, 3x'
            ...
```
