### ISSUE TITLE
Add the file type icons to the download(s) content elements preview in BE

### ISSUE THREAD

**Issue by Aybee** [contao/contao#6370]
Go to online demo CE 'File elements' preview.

![bildschirmfoto am 2017-08-29 um 11 40 48](https://user-images.githubusercontent.com/1143013/29814906-32c8f440-8caf-11e7-9cfe-6d41f2a1b20f.png)

![bildschirmfoto am 2017-08-29 um 11 23 53](https://user-images.githubusercontent.com/1143013/29814913-39f73542-8caf-11e7-8d75-8954ace52bd2.png)

It would be nice, if the BE preview of CEs download and downloads would show the file type icons. The classes are already there. 
```html
<div class="ce_downloads block">
  <h2>Download List Example</h2>
  <ul>
    <li class="download-element ext-jpg"> <a href="..." title="">DSC_5276.jpg <span class="size">(41,0 KiB)</span></a></li>
    <li class="download-element ext-jpg"> <a href="..." title="">DSC_5316.jpg <span class="size">(29,8 KiB)</span></a></li>
    <li class="download-element ext-jpg"> <a href="..." title="">DSC_5403.jpg <span class="size">(35,6 KiB)</span></a></li>
  </ul>
</div>
```
You can test it with devtools and this CSS. It's the CSS from icons.css
https://github.com/contao-components/contao/blob/master/css/icons.css
with modified path to the svg.
```css
.download-element {
	padding:3px 6px 3px 22px;
	background:url("assets/contao/images/iconPLAIN.svg") left center no-repeat;
}
ul.enclosure {
	padding-left:0;
}
li.download-element {
	list-style-type:none;
}
/* Application files */
.ext-jpg {
	background-image:url("assets/contao/images/iconJPG.svg");
}
/* snip */
```
