### ISSUE TITLE
Galerie-Element: Anzahl der Bilder anzeigen

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#6377]
In Contao 3 war es noch einfach. In einer Zeile sind 8 Bilder, da war die Gesamtanzahl leicht zu ermitteln. In Contao 4 bereitet das Mühe, weil je nach Einstellung eine unterschiedliche Anzahl je Zeile angezeigt wird.
![galerie-bildanzahl](https://user-images.githubusercontent.com/4542730/38857985-e666d57c-422a-11e8-99d3-ab983f8be253.jpg)
Es wäre schön, wenn irgendwo angezeigt würde, wieviel Bilder eingebunden sind.

**Comment by leofeyer** [comment]
> weil je nach Einstellung eine unterschiedliche Anzahl je Zeile angezeigt wird

Ja? Bei mir sind es immer 14 Bilder pro Reihe.

**Comment by asaage** [comment]
14... solange 
- die Backend-Breite im Profil begrentz ist
- ausreichend Platz für 14 Thumbnails da ist
- die Thumbnailgröße nicht verändert wurde...

Vielleicht könnte man einfach das hier ins Backend-css einfügen?

```css
.selector_container ul {
    counter-reset: items;
}
.selector_container ul li {
    counter-increment: items;
}
.selector_container ul::after {
    content: "("counter(items)")";
    display: block;
    clear: both;
}
```

ich fände es großartig, wenn man unter Systemeinstellungen für so kleine Tweaks eine zusätzliche BE-CSS Datei angeben könnte.
