### ISSUE TITLE
config/config.yml

### ISSUE THREAD

**Issue by asaage** [contao/contao#6541]
### Affected version(s)

5.2

### Description

updating to contao 5.2 the following keys are no longer effective:

```yaml
contao:
    locales:
        - en
        - de
```

**Comment by fritzmg** [comment]
What do you mean by that?

**Comment by fritzmg** [comment]
```
config:dump-reference contao locales
# Default configuration for extension with alias: "contao" at path "locales"

# Allows to configure which languages can be used in the Contao back end. Defaults to all languages for which a translation exists.
locales:              [] # Deprecated (Since contao/core-bundle 4.12: Using contao.locales is deprecated. Please use contao.intl.enabled_locales instead.)
```

You need to use `contao.intl.enabled_locales`.

**Comment by asaage** [comment]
I used to restrict that but now i have a variety of options:

users profile: 
![image](https://github.com/contao/contao/assets/4138336/d18d1629-0235-4601-809f-f57ac5772487)

**Comment by fritzmg** [comment]
Yes, see the comment above.

**Comment by ausi** [comment]
```yaml
contao:
    intl:
        enabled_locales: [en, de]
```
