### ISSUE TITLE
Usibility: file manager: make the selected image stand out better visually

### ISSUE THREAD

**Issue by tuxenberger** [contao/contao#6555]
### Description

I often work as an editor on various extensive projects. One of the frequent requirements: Please replace image file A with B in an existing content element. Here I usually first look in the file manager to see where the file is located and what it is named. With very extensive image directories, the radio button element as the only feature for a selected image is very quickly "scrolled over".

A CSS class, e.g. "selected", is not present in the list for the active element as far as I have seen.

My request/idea: make the active image stand out better visually by using a more extensive color background or something similar. 

Translated with www.DeepL.com/Translator (free version)

**Comment by asaage** [comment]
```css
.picker li:has(input[name^=picker]:checked) {
	outline: var(--green) solid 1px;
	/*
	outline-offset: -1px;
	box-shadow: inset 0 0 0 1px var(--green);
	background-color: var(--green);
	*/
}
```
Works for checkboxes and radiobuttons in include-element, include-article, hyperlink, image, gallery, download(s)...
Styling is however debateable - in some cases negative outline-offset or inset box-shadow does not work because background-color of a child gets in the way. Similar problem with using background-color.
And of course browsersupport for the :has() selector 🤷‍♂️
