### ISSUE TITLE
It is currently impossible to register an InsertTag with tags via services.yml

### ISSUE THREAD

**Issue by moonfr34k** [contao/contao#7185]
### Affected version(s)

5.3.7

### Description

If you register a new InsertTag in the services.yml as follows, you get an exception "Invalid insert tag name''" because the name of the InsertTag is missing. However, this cannot be stored at all, since "contao.insert_tag" must also be stored as tag "name" for it to work.

  Example\ContaoBundle\Experts\InsertTag\ExampleInsertTag:
    tags:
      - { name: contao.insert_tag }

**Comment by Toflar** [comment]
You can use

```yaml
Example\ContaoBundle\Experts\InsertTag\ExampleInsertTag:
    tags:
        - contao.insert_tag: { name: 'my_insert_tag' }
```

as documented in https://symfony.com/doc/current/service_container/tags.html (the hint box if `name` is already used :-)).
