### ISSUE TITLE
Introduce separate `contao_mailer` messenger transport

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7495]
In many shared hosting environments the amount of emails you can send is limited (or limited by the SMTP). For example, on webgo shared hostings you can send 50 per hour, on Hetzner 500 emails per hour.

Starting with Symfony 6 you can assign a [Rate Limiter](https://symfony.com/doc/6.4/rate_limiter.html) to a [Messenger Transport](https://symfony.com/doc/6.4/messenger.html#rate-limited-transport) and thus by routing emails to the messenger bus you can limit the amount of emails per time frame.

In order to take advantage of this you have to:

* Define a messenger transport for emails
* Route emails to this messenger transport
* Create a rate limiter
* Assign the rate limiter to the messenger transport
 
```yaml
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

    rate_limiter:
        mailer:
            policy: fixed_window
            limit: 50
            interval: 1 hour

    messenger:
        transports:
            mailer: 
                dsn: doctrine://default?queue_name=mailer
                rate_limiter: mailer

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': mailer
```

Within the Contao Managed Edition emails are already routed to the `contao_prio_high` messenger transport [by default](https://github.com/contao/contao/blob/901a52a084c517221aed91296eb521416297d633/manager-bundle/skeleton/config/config.yaml#L54).

However, if you now want to rate limit the emails, within this default configuration, you'd now have to rate limit the `contao_prio_high` messenger transport - which is not ideal, as you don't really want to rate limit your high priority queue in general.

Alternatively you would have to:

* Create a _new_ messenger transport just for emails
* Route the emails via this transport instead
* Add the rate limiter to that transport
* Add the new transport to the `contao.messenger.workers`

```yaml
framework:
    rate_limiter:
        mailer:
            policy: fixed_window
            limit: 50
            interval: 1 hour

    messenger:
        transports:
            mailer: 
                dsn: doctrine://default?table_name=tl_message_queue&queue_name=mailer&auto_setup=false
                rate_limiter: mailer

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': mailer

contao:
    messenger:
        workers:
            -
                transports:
                    - contao_prio_high
                options:
                    - '--time-limit=60'
                    - '--sleep=5'
                autoscale:
                    desired_size: 5
                    max: 10
                    enabled: true
            -
                transports:
                    - contao_prio_normal
                options:
                    - '--time-limit=60'
                    - '--sleep=10'
                autoscale:
                    desired_size: 10
                    max: 10
                    enabled: true
            -
                transports:
                    - contao_prio_low
                options:
                    - '--time-limit=60'
                    - '--sleep=20'
                autoscale:
                    desired_size: 20
                    max: 10
                    enabled: true
            -
                transports:
                    - mailer
                options:
                    - '--time-limit=60'
                    - '--sleep=5'
                autoscale:
                    desired_size: 5
                    max: 10
                    enabled: true
```

Which is a bit cumbersome.

My thought was thus whether we should create a separate `contao_mailer` messenger transport by default, to make it easier to assign a rate limiter to it. Then the app config in the Contao Managed Edition would be reduced to

``` yaml
framework:
    rate_limiter:
        contao_mailer:
            policy: fixed_window
            limit: 50
            interval: 1 hour

    messenger:
        transports:
            contao_mailer: 
                rate_limiter: contao_mailer
```

wdyt?
