### ISSUE TITLE
Support predefined image sizes in {{picture::}} tag

### ISSUE THREAD

**Issue by simonreitinger** [contao/contao#777]
**Description**  
I just noticed that it's currently not possible to pass a predefined size from the newly added config (https://github.com/contao/contao/pull/537).

**Example**  
```yml
# config.yml

contao:
    image:
        sizes:
            news_list:
                items:
                  - width: 0
                    height: 0
                    resizeMode: 'crop'
                    densities: '1x,2x'
                    media: '(min-width: 993px)'
                  - width: 0
                    height: 0
                    resizeMode: 'crop'
                    densities: '1x,2x'
                    media: '(min-width: 768px) and (max-width: 992px)'
                  - width: 0
                    height: 0
                    resizeMode: 'crop'
                    densities: '1x,2x'
                    media: '(max-width: 767px)'
```

```html
<!-- my_template.html5 -->
<figure class="image_container">
    {{picture::<?= $this->path ?>?size=news_list}}
</figure>
```

I'll create a PR in the next days if that is ok to implement this feature.
