### ISSUE TITLE
Unwanted normalization for the `resampling-filter` Imagine option

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#7777]
### Affected version(s)

4.13, 5.x

### Description

With the following config:

```yaml
contao:
    image:
        imagine_options:
            resampling-filter: lanczos
```

I get the error `Unrecognized option "resampling_filter" under "contao.image.imagine_options". Did you mean "resampling-filter"?` because dashes are normalized to underscores.

I think the `normalizeKeys(false)` option needs to be added to the `imagine_options`:
https://symfony.com/doc/current/components/config/definition.html#array-node-options
