### ISSUE TITLE
Labelling select list headline

### ISSUE THREAD

**Issue by bekanntmacher** [contao/contao#7907]
### Description

Not all editors know the meaning of h1... h6. I suggest we name them analogue to the WYSIWYG: Headline 1, Headline 2 and so on

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/d38967ac-4180-4edb-a1cf-d23485cb30a2" />

**Comment by fritzmg** [comment]
I am not sure this is needed in Contao in general. However, you could do the following in projects for your customers:

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['fields']['headline']['reference'] = &$GLOBALS['TL_LANG']['tl_content']['headlineUnits'];
```
```yaml
# translations/contao_tl_content.en.yaml
tl_content:
    headlineUnits:
        h1: Headline 1
        h2: Headline 2
        h3: Headline 3
        h4: Headline 4
        h5: Headline 5
        h6: Headline 6
```
