### ISSUE TITLE
The menu in the picker is broken

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7912]
### Affected version(s)

5.5

### Description

<img width="901" alt="" src="https://github.com/user-attachments/assets/2ee6746e-7418-420f-a0ad-8f9b4e38f61b" />

**Comment by zoglo** [comment]
We should be able to fix it with a very specific selector since I don't know if it would otherwise cause side effects:

```css
.tl_right:has(.operations + [name="picker"]) {
    display: flex;
}
```

![Image](https://github.com/user-attachments/assets/91a9a698-912f-4dae-91f7-6bb7fe7c7faf)

![Image](https://github.com/user-attachments/assets/562527c8-5d13-4ab8-99d3-46be5e56ccd8)
