### ISSUE TITLE
Optimierung zur Darstellung der Beschreibung in der Versionsübersicht

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#830]
In der Versionsübersicht auf der Startseite des Backends wird der Text in der Spalte Beschreibung derzeit nach einer festen Anzahl an Zeichen abgeschnitten.

Im Sinne von Responsive Design ist es mit CSS möglich, den vollständigen Text auszugeben und diesen dann dynamisch abhängig vom zur Verfügung stehenden Platz abzuschneiden. Wenn eine Kürzung notwendig ist, werden dabei ebenfalls `…` angezeigt, um dies erkennbar zu machen.

CSS für die Zellen der Spalte Beschreibung:
```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
max-width: 0;
```

**Comment by Mynyx** [comment]
Leider doch nicht mit allen Browsern kompatibel.

**Comment by leofeyer** [comment]
In welchen Browsern ging es denn nicht? Laut caniuse.com sollten das eigentlich alle Browser können: https://caniuse.com/#feat=text-overflow

**Comment by m-vo** [comment]
Es sollte gut funktionieren bei reinem Text (`<p style="text-overflow: ellipsis;">...</p>`) - die Browser unterscheiden sich aber teilweise sehr, wenn es um komplexere Inhalte wie nested blocks, floats, ... geht (das Verhalten ist imho nicht vollumfänglich spezifiziert).

**Comment by leofeyer** [comment]
Ah, es geht nicht, weil es ein `<td>`-Element ist und kein `<p>`.

**Comment by ausi** [comment]
In meinem Test hat es auch mit dem `<td>`-Element geklappt, sowohl im Firefox als auch im Chrome.

**Comment by leofeyer** [comment]
Stimmt. Ich hatte wohl das `max-width: 0` vergessen. 🙄

**Comment by leofeyer** [comment]
Ich hab das jetzt nochmal getestet und bin irgendwie nicht so ganz überzeugt, weil die beiden Spalten dadurch – zumindest in Chrome – sehr schmal angezeigt wurden, obwohl eigentlich genug Platz wäre:

<img width="1211" alt="" src="https://user-images.githubusercontent.com/1192057/68759997-200aa280-0611-11ea-83d6-2b36d35e1e78.png">

Um das zu kompensieren, habe ich eine Breite zugewiesen:

```css
#tl_versions td:nth-child(3),#tl_versions td:nth-child(5) {
	overflow:hidden;
	text-overflow:ellipsis;
	white-space:nowrap;
	max-width:0;
}
#tl_versions td:nth-child(3) {
	width:15%;
}
#tl_versions td:nth-child(5) {
	width:40%;
}
```

Dadurch sieht die Tabelle wieder einigermaßen normal aus, aber die Spalten werden immer noch abgeschnitten, obwohl eigentlich genug Platz wäre:

<img width="1213" alt="" src="https://user-images.githubusercontent.com/1192057/68759759-9d81e300-0610-11ea-81ff-f7bf48ecb057.png">

Fällt einem von euch ein, wie man das besser machen kann?

**Comment by m-vo** [comment]
Das geht denke ich nicht - `text-overflow: ellipsis` braucht die Größe des Contents.

Alternativ lässt sich höchstens sowas machen (Tradeoff: keine Ellipse für Text der mehrzeilig werden würde, dafür automatische Verteilung):

```css
tr {
  display: flex;
}

td {
  display: block;
  height: 1em;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
